version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3lambdaevent"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-141m7qe2isa4k"
s3_prefix = "s3lambdaevent"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
disable_rollback = true
